name: OIDC CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_container:
    name: Deploy Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker to Authenticate with Artifact Registry
        run: |
          echo "Configuring Docker authentication for Artifact Registry..."
          gcloud auth configure-docker us-east1-docker.pkg.dev
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-east1-docker.pkg.dev

      - name: Pull Image from Docker Hub
        run: |
          echo "Pulling nginx:latest image from Docker Hub..."
          docker pull nginx:latest

      - name: Tag Image for Google Artifact Registry
        run: |
          echo "Tagging nginx:latest for Google Artifact Registry..."
          docker tag nginx:latest \
          us-east1-docker.pkg.dev/csagi-439110/no-code-architects-toolkit/nginx:latest

      - name: Push Image to Google Artifact Registry
        run: |
          echo "Pushing nginx:latest to Google Artifact Registry..."
          docker push us-east1-docker.pkg.dev/csagi-439110/no-code-architects-toolkit/nginx:latest